### ISSUE TITLE
Error installing Script Extender file 'DWrite.dll' to bin folder

### ISSUE THREAD

**Issue by kantosaru** [Norbyte/bg3se#476]
### I have attempted solutions to common problems

Yes

### I have checked that my game version is supported

Yes

### OS

Windows 11

### Platform

Steam

### Description

Unable to install the 'DWrite.dll' file in the bin folder. Not sure why this is happening, as I've been able to install it before on an different computer.

### Indications

The Script Extender file itself is having issues being installed to the bin folder. I currently have no other mods installed.

### Diagnostic Files

[BG3 Diagnostic Data.txt](https://github.com/user-attachments/files/17802838/BG3.Diagnostic.Data.txt)

**Error Log from BG3 Mod Manager**

[MainWindowViewModel.cs:DownloadScriptExtender(517)] Error extracting package: System.IO.DirectoryNotFoundException: (3) The system cannot find the path specified: [E:\SteamLibrary\steamapps\common\Baldurs Gate 3\bin\DWrite.dll]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.NativeError.ThrowException(Int32 errorCode, Nullable`1 isFolder, String readPath)
   at Alphaleonis.Win32.Filesystem.NativeMethods.CloseHandleAndPossiblyThrowException(SafeHandle handle, Int32 lastError, Nullable`1 isFolder, String path, Boolean throwException)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, Nullable`1 isFolder, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, Boolean continueOnException, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.CreateFileStreamCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, PathFormat pathFormat)
   at DivinityModManager.ViewModels.MainWindowViewModel.<>c__DisplayClass396_0.<<DownloadScriptExtender>b__0>d.MoveNext()
[MainWindowViewModel.cs:OnMainProgressComplete(2930)] Main progress is complete.
[MainWindowViewModel.cs:ShowAlert(4258)] Error occurred when installing the Extender updater DWrite.dll - Check the log
[MainWindowViewModel.cs:DownloadScriptExtender(517)] Error extracting package: System.IO.DirectoryNotFoundException: (3) The system cannot find the path specified: [E:\SteamLibrary\steamapps\common\Baldurs Gate 3\bin\DWrite.dll]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.NativeError.ThrowException(Int32 errorCode, Nullable`1 isFolder, String readPath)
   at Alphaleonis.Win32.Filesystem.NativeMethods.CloseHandleAndPossiblyThrowException(SafeHandle handle, Int32 lastError, Nullable`1 isFolder, String path, Boolean throwException)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, Nullable`1 isFolder, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, Boolean continueOnException, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.CreateFileStreamCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, PathFormat pathFormat)
   at DivinityModManager.ViewModels.MainWindowViewModel.<>c__DisplayClass396_0.<<DownloadScriptExtender>b__0>d.MoveNext()
[MainWindowViewModel.cs:OnMainProgressComplete(2930)] Main progress is complete.
[MainWindowViewModel.cs:ShowAlert(4258)] Error occurred when installing the Extender updater DWrite.dll - Check the log

### Steps to Reproduce

1. Download latest version of Script Extender
2. Extract directly into BG3 bin folder

**OR**

1. Download and extract latest version of Script Extender
2. Copy 'DWrite.dll' into BG3 bin folder

**OR**

1. Run BG3 Mod Manager as an administrator
2. Open 'Tool' menu and initiate the 'Download & Extract the Script Extender...' option

### Expected Behavior

DWrite.dll should quickly extract/copy into the bin folder without issue.

### Actual Behavior

System initiates the copy/extraction of the 'DWrite.dll' file, but freezes at 0% with no progress across an indefinite amount of time.
When attempting to install through BG3 Mod Manager, an error message pops up and an error log is generated.

**Comment by Norbyte** [comment]
This is BG3 Mod Manager issue, rather than an SE issue.
